/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

/**
 * A versioned semantic scene for one drawing revision.
 */
export interface DrawingScene {
  documentId: string;
  layers: Layer[];
  objects: (PipeSegment | Junction | SymbolObject | Annotation | Dimension | UnknownMark)[];
  page: Page;
  parentRevisionId?: string;
  profileId: "piping_isometric";
  relationships: Relationship[];
  revisionId: string;
  schemaVersion: string;
}
/**
 * A drawing layer with its source and render colors.
 */
export interface Layer {
  id: string;
  name: string;
  renderColor: string;
  sourceColor: string;
}
/**
 * A pipe run between two junctions.
 */
export interface PipeSegment {
  endNodeId: string;
  id: string;
  interpretation: Interpretation;
  layerId: string;
  originalPrimitive?: OriginalPrimitive;
  primitive: LinePrimitive;
  startNodeId: string;
  type: "pipe_segment";
}
/**
 * Review state, optional calibrated score, and supporting evidence.
 */
export interface Interpretation {
  evidence: Evidence[];
  score?: number;
  state: "machine" | "confirmed" | "rejected" | "unknown";
}
/**
 * Source-image support for an interpretation.
 */
export interface Evidence {
  artifactId: string;
  observations: {
    [k: string]: boolean | number | string;
  };
  /**
   * @minItems 3
   */
  sourcePolygon: [SourcePoint, SourcePoint, SourcePoint, ...SourcePoint[]];
  stage: string;
}
/**
 * A point in immutable input pixels, before EXIF orientation.
 */
export interface SourcePoint {
  x: number;
  y: number;
}
/**
 * The detected line before snapping to junctions.
 */
export interface OriginalPrimitive {
  end: PagePoint;
  start: PagePoint;
}
/**
 * A point in rectified page pixels.
 */
export interface PagePoint {
  x: number;
  y: number;
}
/**
 * A straight line in page coordinates.
 */
export interface LinePrimitive {
  end: PagePoint;
  kind: "line";
  start: PagePoint;
}
/**
 * A pipe node: endpoint, elbow, tee, crossing, or unknown.
 */
export interface Junction {
  id: string;
  interpretation: Interpretation;
  kind: "endpoint" | "elbow" | "tee" | "crossing" | "unknown";
  layerId: string;
  position: PagePoint;
  type: "junction";
}
/**
 * A library symbol; each port maps to a junction ID or null if unresolved.
 */
export interface SymbolObject {
  anchor: PagePoint;
  id: string;
  interpretation: Interpretation;
  layerId: string;
  portNodeIds: {
    [k: string]: string | null;
  };
  rotationDegrees: number;
  symbolId: string;
  type: "symbol";
}
/**
 * Text on the drawing, keeping recognized and normalized forms.
 */
export interface Annotation {
  alternatives: string[];
  anchor: PagePoint;
  id: string;
  interpretation: Interpretation;
  layerId: string;
  normalizedText: string;
  recognizedText: string;
  targetObjectId?: string;
  type: "annotation";
}
/**
 * A dimension; parsed value and unit are independent of pixel span.
 */
export interface Dimension {
  displayText: string;
  id: string;
  interpretation: Interpretation;
  layerId: string;
  parsedValue?: number;
  targetObjectIds: string[];
  type: "dimension";
  unit?: string;
  witnessEnd: PagePoint;
  witnessStart: PagePoint;
}
/**
 * An unresolved mark kept for review.
 */
export interface UnknownMark {
  candidateLabels: string[];
  id: string;
  interpretation: Interpretation;
  layerId: string;
  sourceCropId: string;
  type: "unknown_mark";
}
/**
 * Source, display, and page sizes with row-major 3x3 transforms.
 */
export interface Page {
  displayHeightPx: number;
  /**
   * @minItems 9
   * @maxItems 9
   */
  displayToSource: [number, number, number, number, number, number, number, number, number];
  displayWidthPx: number;
  heightPx: number;
  /**
   * @minItems 9
   * @maxItems 9
   */
  pageToSource: [number, number, number, number, number, number, number, number, number];
  sourceHeightPx: number;
  /**
   * @minItems 9
   * @maxItems 9
   */
  sourceToDisplay: [number, number, number, number, number, number, number, number, number];
  /**
   * @minItems 9
   * @maxItems 9
   */
  sourceToPage: [number, number, number, number, number, number, number, number, number];
  sourceWidthPx: number;
  widthPx: number;
}
/**
 * A non-connectivity link between two scene objects.
 */
export interface Relationship {
  fromId: string;
  id: string;
  interpretation: Interpretation;
  toId: string;
  type: "annotates" | "measures" | "callout_targets";
}
