"""Generate the DrawingScene JSON Schema, TypeScript types, and TS fixtures.

Usage (from the repository root)::

    PYTHONPATH=packages/pipeline .venv/bin/python -m isometric_pipeline.scene.generate
    PYTHONPATH=packages/pipeline .venv/bin/python -m isometric_pipeline.scene.generate \
        --check

The default mode rewrites the committed files in ``packages/scene-schema``.
``--check`` regenerates into a temporary directory and exits non-zero if any
committed file differs.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import shlex
import shutil
import subprocess
import sys
import tempfile
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from .models import DrawingScene
from .serialization import dump_scene

REPO_ROOT = Path(__file__).resolve().parents[4]
PACKAGE_DIR = REPO_ROOT / "packages" / "scene-schema"
PACKAGE_NAME = "@isometric/scene-schema"

SCHEMA_FILE = Path("drawing-scene.schema.json")
TYPES_FILE = Path("src/drawing-scene.ts")
FIXTURES_FILE = Path("test/fixtures.generated.ts")
GENERATED_FILES = (SCHEMA_FILE, TYPES_FILE, FIXTURES_FILE)

VALID_FIXTURES = Path("fixtures/valid")
GENERATE_TYPES_SCRIPT = "generate:types"

FIXTURES_HEADER = """\
/**
 * This file was generated by `python -m isometric_pipeline.scene.generate`.
 * DO NOT MODIFY IT BY HAND. Instead, edit fixtures/valid and regenerate.
 */

import type {DrawingScene} from "../src/drawing-scene.js";
"""

_IDENTIFIER = re.compile(r"^[A-Za-z_$][A-Za-z0-9_$]*$")


class GenerationError(RuntimeError):
    """A generation step failed."""


def schema_text() -> str:
    schema = DrawingScene.model_json_schema(by_alias=True)
    return json.dumps(schema, sort_keys=True, indent=2, ensure_ascii=False) + "\n"


def _camel_name(stem: str) -> str:
    head, *rest = re.split(r"[-_]", stem)
    name = head + "".join(part[:1].upper() + part[1:] for part in rest)
    if not _IDENTIFIER.match(name):
        raise GenerationError(f"fixture name {stem!r} is not a valid identifier")
    return name


def _reject_constant(token: str) -> Any:
    raise GenerationError(f"non-finite number {token} in fixture")


def fixtures_text(fixtures_dir: Path) -> str:
    paths = sorted(fixtures_dir.glob("*.json"))
    if not paths:
        raise GenerationError(f"no valid fixtures in {fixtures_dir}")
    blocks = [FIXTURES_HEADER]
    for path in paths:
        raw = json.loads(
            path.read_text(encoding="utf-8"), parse_constant=_reject_constant
        )
        canonical = dump_scene(DrawingScene.model_validate(raw)).rstrip("\n")
        blocks.append(
            f"export const {_camel_name(path.stem)}: DrawingScene = {canonical};\n"
        )
    return "\n".join(blocks)


def _run(args: Sequence[str]) -> None:
    if shutil.which(args[0]) is None:
        raise GenerationError(f"{args[0]} is not on PATH")
    result = subprocess.run(
        args, cwd=REPO_ROOT, capture_output=True, text=True, check=False
    )
    if result.returncode != 0:
        raise GenerationError(
            f"{shlex.join(args)} exited {result.returncode}\n"
            f"{result.stdout}{result.stderr}"
        )


def _types_command(schema: Path, output: Path) -> list[str]:
    """Reuse the package script's json2ts options with different paths."""
    manifest = json.loads((PACKAGE_DIR / "package.json").read_text(encoding="utf-8"))
    tokens = shlex.split(manifest["scripts"][GENERATE_TYPES_SCRIPT])
    replacements = {str(SCHEMA_FILE): str(schema), str(TYPES_FILE): str(output)}
    if not set(replacements) <= set(tokens):
        raise GenerationError(
            f"{GENERATE_TYPES_SCRIPT} must reference {SCHEMA_FILE} and {TYPES_FILE}"
        )
    return [replacements.get(token, token) for token in tokens]


def _write(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def write() -> None:
    """Regenerate the committed schema, types, and fixtures in place."""
    _write(PACKAGE_DIR / SCHEMA_FILE, schema_text())
    _run(["pnpm", "--filter", PACKAGE_NAME, "run", GENERATE_TYPES_SCRIPT])
    _write(PACKAGE_DIR / FIXTURES_FILE, fixtures_text(PACKAGE_DIR / VALID_FIXTURES))


def generate_into(out_dir: Path, fixtures_dir: Path) -> None:
    """Generate every output under ``out_dir`` without touching the package."""
    _write(out_dir / SCHEMA_FILE, schema_text())
    types_path = out_dir / TYPES_FILE
    types_path.parent.mkdir(parents=True, exist_ok=True)
    command = _types_command(out_dir / SCHEMA_FILE, types_path)
    _run(["pnpm", "--filter", PACKAGE_NAME, "exec", *command])
    _write(out_dir / FIXTURES_FILE, fixtures_text(fixtures_dir))


def stale_files(committed_dir: Path, generated_dir: Path) -> dict[Path, str]:
    """Map each differing file to a unified diff (committed -> generated)."""
    stale: dict[Path, str] = {}
    for relative in GENERATED_FILES:
        expected = (generated_dir / relative).read_text(encoding="utf-8")
        committed_path = committed_dir / relative
        if not committed_path.is_file():
            stale[relative] = f"{relative}: missing\n"
            continue
        actual = committed_path.read_text(encoding="utf-8")
        if actual != expected:
            stale[relative] = "".join(
                difflib.unified_diff(
                    actual.splitlines(keepends=True),
                    expected.splitlines(keepends=True),
                    fromfile=f"committed/{relative}",
                    tofile=f"generated/{relative}",
                )
            )
    return stale


def check(package_dir: Path = PACKAGE_DIR) -> dict[Path, str]:
    with tempfile.TemporaryDirectory(prefix="scene-schema-") as tmp:
        generated_dir = Path(tmp)
        generate_into(generated_dir, package_dir / VALID_FIXTURES)
        return stale_files(package_dir, generated_dir)


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(
        prog="python -m isometric_pipeline.scene.generate", description=__doc__
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed generated files are out of date",
    )
    args = parser.parse_args(argv)
    try:
        if not args.check:
            write()
            return 0
        stale = check(PACKAGE_DIR)
    except GenerationError as exc:
        print(f"scene generation failed: {exc}", file=sys.stderr)
        return 2
    if not stale:
        return 0
    for diff in stale.values():
        sys.stderr.write(diff if diff.endswith("\n") else diff + "\n")
    names = ", ".join(str(path) for path in stale)
    print(
        f"stale generated files: {names}\n"
        "run: PYTHONPATH=packages/pipeline .venv/bin/python "
        "-m isometric_pipeline.scene.generate",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    raise SystemExit(main())
